---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint .
platforms:
  - name: ubuntu-16.04
    image: solita/ubuntu-systemd:16.04
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint: ansible-lint
scenario:
  name: install-only
verifier:
  name: testinfra
  lint: flake8
