---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu-16.04
    image: solita/ubuntu-systemd:16.04
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
scenario:
  name: install-only
verifier:
  name: testinfra
  lint:
    name: flake8
