---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  flake8
platforms:
  - name: nginx-install-only-ubuntu-22.04
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: nginx-install-only-ubuntu-24.04
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: nginx-install-only-ubuntu-26.04
    image: geerlingguy/docker-ubuntu2604-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
  lint:
    name: ansible-lint
    enabled: false
scenario:
  name: install-only
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
