# nginx/tasks/configure.yml

- name: Nginx | Make sure the mime.types file is up to date
  copy:
    src: mime.types
    dest: "{{nginx_dir}}/mime.types"
    owner: root
    group: root
    mode: 0644

- name: Nginx | Check for existence of Nginx configuration
  stat:
    path: "{{nginx_dir}}/nginx.conf"
  register: nginx_config

- name: Nginx | Make sure the Nginx configuration is updated
  template:
    src: nginx.conf.j2
    dest: "{{nginx_dir}}/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: Nginx | Check if Nginx is running
  shell: "service nginx status"
  ignore_errors: yes
  register: nginx_started_check

- name: Nginx | Notify Nginx service start
  command: "echo Nginx service scheduled to start"
  when: nginx_started_check.rc != 0
  notify:
   - start nginx

- name: Nginx | Enable the Nginx service
  service:
    name: nginx
    enabled: yes
