---
- name: Make sure /etc/nginx/conf.d Exists
  file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy over the load balancer config
  template:
    src: load-balancer.conf.j2
    dest: /etc/nginx/conf.d/load-balancer-{{ item.upstream_name }}.conf
    mode: 0644
  with_items: "{{ nginx_loadbalancers }}"
