- name: Make sure /etc/nginx/conf.d Exists
  file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Include load balancer
  template:
    src: load-balancers.conf.j2
    dest: /etc/nginx/conf.d/load-balancers.conf
    mode: 0644
  when: nginx_loadbalancers is defined