---
# file: nginx/tasks/main.yml

- include: package.yml
  when: nginx_install_method == "package"
- include: source.yml
  when: nginx_install_method == "source"
- include: scripts.yml
- include: configure.yml
- include: default_site.yml
- include: sites.yml
- include: loadbalancers.yml
- include: basic-auth.yml
  when: nginx_basic_auth_files|length > 0
- include: monit.yml
  when: monit_protection is defined and monit_protection == true
- include: monitoring.yml
  when: nginx_enable_monitoring is defined and nginx_enable_monitoring == true
