---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Nginx | Make sure the ansible required dependencies are installed
  apt:
    name:
      - python3-pycurl
      - dirmngr
      - gnupg
      - wget
    state: present

- name: Add nginx GPG key
  command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ABF5BD827BD9BF62

- name: Add Nginx APT repository
  apt_repository:
    repo: "deb https://nginx.org/packages/ubuntu/ {{ ubuntu_release }} nginx"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Nginx | Download the libssl1.1 package
  get_url:
    url: "http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb"
    dest: "/tmp/libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb"

- name: Install deb
  command: apt install /tmp/libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb -y --allow-downgrades
  become: true

- name: Nginx | Make sure nginx is installed (package)
  apt:
    pkg: "{{nginx}}"
    state: present
  notify:
    - restart nginx

- name: Nginx | Make sure the NGINX service is enabled
  service:
    name: nginx
    enabled: true

- include_tasks: directories.yml
