---
# file: nginx/tasks/package.yml

- name: Nginx | Make sure the ansible required dependencies are installed
  apt:
    name:
      - python3-pycurl
      - dirmngr
      - gnupg
    state: present

#  make the KEY_ID a var
- name: Add nginx GPG key
  command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ABF5BD827BD9BF62

- name: Add Nginx APT repository
  apt_repository:
    repo: "deb https://nginx.org/packages/ubuntu/ {{ ubuntu_release }} nginx"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Nginx | Make sure nginx is installed (package)
  apt:
    pkg: "{{nginx}}"
    state: present
  notify:
    - restart nginx

- name: Nginx | Make sure the NGINX service is enabled
  service:
    name: nginx
    enabled: true

- include: directories.yml
