---
# file: nginx/tasks/package.yml

- name: Nginx | Make sure the ansible required dependencies are installed
  apt:
    pkg: python-pycurl
    state: present

- name: Nginx | Add the nginx repository
  apt_repository:
    repo: ppa:nginx/stable
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version is version_compare('20.04', '<')

- name: Nginx | Make sure nginx is installed (package)
  apt:
    pkg: "{{nginx}}"
    state: present
  notify:
    - restart nginx

- name: Nginx | Make sure the NGINX service is enabled
  service:
    name: nginx
    enabled: true

- include: directories.yml
