---
# file: nginx/tasks/package.yml

- name: Nginx | Make sure the ansible required dependencies are installed
  apt:
    name:
      - python3-pycurl
      - dirmngr
      - gnupg
    state: present

- name: Nginx | Add the nginx repository
  apt_repository:
    repo: "{{ nginx_apt_ppa }}"
  when:
    - nginx_apt_ppa | length > 0
    - ansible_distribution_version is version("22.04", "<")

- name: Nginx | Make sure nginx is installed (package)
  apt:
    pkg: "{{nginx}}"
    state: present
  notify:
    - restart nginx

- name: Nginx | Make sure the NGINX service is enabled
  service:
    name: nginx
    enabled: true

- include: directories.yml
