---
# file: nginx/tasks/ssl.yml
- block:
  - name: Copy secure ssl configuration
    template:
      src: secure_ssl.conf.j2
      dest: "{{ nginx_dir }}/{{ site.server.ssl.conf }}"
      owner: root
      group: root
      mode: 0644
    notify:
      - restart nginx

  - name: Ensure ssl directory is present
    file:
      state: directory
      path: "{{ nginx_ssl_dir }}"
      owner: root
      group: root
      mode: 0700

  - name: Copy SSL certificate
    copy:
      src: "{{ site.server.ssl.src_dir }}/{{ site.server.ssl.cert }}"
      dest: "{{ nginx_ssl_dir }}/{{ site.server.ssl.cert }}"
      mode: 0600
      remote_src: "{{ site.server.ssl.remote_src | default('no') }}"
    notify:
      - restart nginx
    when: site.server.ssl.create_symlink is not defined or site.server.ssl.create_symlink == false

  - name: Copy SSL key
    copy:
      src: "{{ site.server.ssl.src_dir }}/{{ site.server.ssl.key }}"
      dest: "{{ nginx_ssl_dir }}/{{ site.server.ssl.key }}"
      mode: 0600
      remote_src: "{{ site.server.ssl.remote_src | default('no') }}"
    notify:
      - restart nginx
    when: site.server.ssl.create_symlink is not defined or site.server.ssl.create_symlink == false

  - name: Create SSL certificate symlink
    file:
      src: "{{ site.server.ssl.src_dir }}/{{ site.server.ssl.cert }}"
      dest: "{{ nginx_ssl_dir }}/{{ site.server.ssl.cert }}"
      state: link
      force: true
    notify:
      - restart nginx
    when: site.server.ssl.create_symlink is defined and site.server.ssl.create_symlink == true

  - name: Create SSL key symlink
    file:
      src: "{{ site.server.ssl.src_dir }}/{{ site.server.ssl.key }}"
      dest: "{{ nginx_ssl_dir }}/{{ site.server.ssl.key }}"
      state: link
      force: true
    notify:
      - restart nginx
    when: site.server.ssl.create_symlink is defined and site.server.ssl.create_symlink == true

  - name: Add certificate passphrase to SSL passphrases file
    lineinfile:
      path: "{{ nginx_ssl_passphrase_path }}"
      line: "{{ site.server.ssl.ssl_passphrase }}"
      create: true
    notify:
      - restart nginx
    when: site.server.ssl.ssl_passphrase is defined

  - name: Generate secure Diffie Hellman ephemeral parameters
    command: openssl dhparam -dsaparam -out /etc/ssl/certs/dhparam.pem 4096 creates=/etc/ssl/certs/dhparam.pem
  when: site.server.ssl.enabled == True
