# file: nginx/tasks/ssl.yml
- block:
  - name: Copy secure ssl configuration
    template:
      src: secure_ssl.conf.j2
      dest: "{{ nginx_dir }}/{{ site.server.ssl.conf }}"
      owner: root
      group: root
      mode: 0644
    notify:
      - restart nginx

  - name: Ensure ssl directory is present
    file:
      state: directory
      path: /etc/nginx/ssl
      owner: root
      mode: 0700

  - name: Copy SSL certificate
    copy:
      src: "{{ site.server.ssl.src_dir }}/{{ site.server.ssl.cert }}"
      dest: "/etc/nginx/ssl/{{ site.server.ssl.cert }}"
      mode: 0600
    notify:
      - restart nginx

  - name: Copy SSL key
    copy:
      src: "{{ site.server.ssl.src_dir }}/{{ site.server.ssl.key }}"
      dest: "/etc/nginx/ssl/{{ site.server.ssl.key }}"
      mode: 0600
    notify:
      - restart nginx

  - name: Generate secure Diffie Hellman ephemeral parameters
    command: openssl dhparam -dsaparam -out /etc/ssl/certs/dhparam.pem 4096 creates=/etc/ssl/certs/dhparam.pem
  when: site.server.ssl.enabled == True