# file: nginx/handlers/main.yml
- name: start nginx
  service: name=nginx state=started
  become: yes
  register: nginx_started

- name: restart nginx
  service: name=nginx state=restarted
  become: yes
  when: nginx_started is undefined or nginx_started.changed == False

- name: reload nginx
  service: name=nginx state=reloaded
  become: yes
