# file: nginx/handlers/main.yml
- name: reload nginx
  service: name=nginx state=reloaded
  become: yes

- name: start nginx
  service: name=nginx state=started
  become: yes
  register: nginx_started

- name: restart nginx
  service: name=nginx state=restarted
  become: yes
  when: not nginx_first_start.changed
