---
# file: nginx/handlers/main.yml
- name: reload nginx
  service: name=nginx state=reloaded
  become: true

- name: start nginx
  service: name=nginx state=started enabled=yes
  become: true

- name: restart nginx
  service: name=nginx state=restarted
  become: true
