---
# file: nginx/handlers/main.yml
- name: reload nginx
  service: name=nginx state=reloaded
  become: true

- name: start nginx
  service: name=nginx state=started enabled=yes use=service
  become: true

- name: restart nginx
  service: name=nginx state=restarted enabled=yes use=service
  become: true
