---
dependency:
  name: galaxy
  options:
    ignore-certs: True
driver:
  name: docker
lint: |
  set -e
  yamllint .
  flake8
platforms:
  # - name: nginx-ubuntu-18.04
  #   image: geerlingguy/docker-ubuntu1804-ansible:latest
  #   privileged: true
  #   command: /sbin/init
  #   cgroupns_mode: host
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   env:
  #     LC_ALL: "C.UTF-8"
  #     LANG: "C.UTF-8"
  - name: nginx-ubuntu-20.04
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    env:
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
  # - name: nginx-ubuntu-22.04
  #   image: geerlingguy/docker-ubuntu2204-ansible:latest
  #   privileged: true
  #   command: /sbin/init
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   env:
  #     LC_ALL: "C.UTF-8"
  #     LANG: "C.UTF-8"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
