---
name: CI

on:
  - push

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - install-only
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule "molecule-plugins[docker]" pytest-testinfra ansible docker yamllint flake8

      - name: Lint
        run: |
          yamllint .
          flake8

      - name: Run Molecule tests
        run: molecule test -s "${{ matrix.scenario }}"
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_NO_LOG: "false"
